### PR TITLE
20 common message types

### LINKED ISSUE #20: Generalize sending messages between programs into a single shared rust library
I converted this into an issue so we can discuss how we want to give this shape, and slowly work towards introducing it.

@BaukeWestendorp, I think we discussed that we wanted to create a shared MessageBytes thin wrapper for the 8-byte packages we send around. Then, we can create further wrappers and From and Into implementations to convert between the different semantically loaded types.

If there are any thoughts you have about how we can best go about this, please add them under this issue. I am especially interested in the needs we have as we work with this project.

### PR DESCRIPTION
**Pull request by KoenWestendorp**
On this branch, I have introduced a common Message trait and many of its implementors. These types allow for a more unified mode of communication between _cockpit-frontend_, _cockpit-backend_, _runtime_, _carburetor_, and _linkage_.

Once this PR is fully implemented and merged, it closes #20.

## Todo

- [x] Implement Messages between _linkage-lib_ and _carburetor_.

### CODE REVIEW

**Comment by KoenWestendorp** [comment]
@BaukeWestendorp What do you think about this? The definition of types is in my first commit. This concerns the work done in the _common_ crate. In the second commit you will find the four concrete implementation for the messages between _frontend_ ↔ _backend_  and  _backend_ ↔ _runtime_.

**Comment by KoenWestendorp** [comment]
Also, do you think it will be useful to have a document that describes the byte codes used for the different messages? It might also make sense to not make such a document, and just refer to the source code. In that way, if we ever change something about the numbers in there, the changes are immediately reflected and cannot get out of sync.

**Comment by BaukeWestendorp** [comment]
> @BaukeWestendorp What do you think about this? The definition of types is in my first commit. This concerns the work done in the _common_ crate. In the second commit you will find the four concrete implementation for the messages between _frontend_ ↔ _backend_ and _backend_ ↔ _runtime_.
> 
> If this looks good to you, I will continue with implementing the communication between _linkage_ ↔ _carburetor_. Let me know if any more places come to mind where we can use this same abstraction.

Looks well. It obviously is a lot more code for something simple, but I think It's okay, as the code is a lot more readable this way.

> Also, do you think it will be useful to have a document that describes the byte codes used for the different messages? It might also make sense to not make such a document, and just refer to the source code. In that way, if we ever change something about the numbers in there, the changes are immediately reflected and cannot get out of sync.

I don't think we should do that. At least not now. We could look at it in the future when the project is a lot more robust and things are unlikely to move around again.

**Comment by BaukeWestendorp** [comment]
Looking good @KoenWestendorp! I do have a few questions after implementing FrontendToBackend in Cockpit-Backend though.

Is [common/src/messages/runtime.rs](https://github.com/Impossible-Robotics-5412/linkage/blob/96e45c076647ec6bc519eb2e817db5bf7a9b3749/common/src/messages/runtime.rs#L12-L16) still needed? I can't find any references to it in the code.
Also why is _message_derive_ a separate crate?

**Comment by KoenWestendorp** [comment]
> Is [common/src/messages/runtime.rs](https://github.com/Impossible-Robotics-5412/linkage/blob/96e45c076647ec6bc519eb2e817db5bf7a9b3749/common/src/messages/runtime.rs#L12-L16) still needed? I can't find any references to it in the code.

This is my mistake. I think some weird things happened in the merge. I must have inadvertently removed some of the changes I made. I will remove common/src/messages/runtime.rs .

> Also why is message_derive a separate crate?

_message_derive_ is a separate crate because implementing a procedural macro such as a derive macro is of a special library trait. (See common/message_derive/Cargo.toml and the [lib] header.)

**Pull request merged**
